assignment/urls.py
from django.urls import path
from . import views

app_name = 'assignment'

urlpatterns = [
    path('assign/<str:student_username>', views.assign_student, name='assign_student'),
    path('assignments/', views.assignment_list, name='assignment_list'),
    path('assigned_students/', views.view_assigned_students, name='view_assigned_students'),
    path('initiate_de_registration/<int:student_id>/', views.initiate_de_registration, name='initiate_de_registration'),
	path('approve_de_registration/<int:student_id>/', views.approve_de_registration, name='approve_de_registration'),
]

chat/urls.py
from django.urls import path
from . import views


app_name = 'chat'

urlpatterns = [
    #calls
    path('chat', views.lobby, name='chat'),
    path('room/', views.room),
    path('get_token/', views.getToken),
    path('create_member/', views.createMember),
    path('get_member/', views.getMember),
    path('delete_member/', views.deleteMember),
    #messages
    path('message/', views.CreateRoom, name='create-room'),
    path('private-chat/<int:assignmemt_id>/', views.MessageView, name='private-room'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('',include('users.urls',namespace='users')),
    path('',include('chat.urls',namespace='chat')),
    path('',include('logbook.urls', namespace='logbook')),
    path('',include('assessment.urls', namespace='assessment')),
    path('',include('assignment.urls', namespace='assignment')),
]

assignment/models.py
from django.db import models
from users.models import Student, Employee
from django.utils import timezone
from users.models import User

class Assignment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    lecturer = models.ForeignKey(Employee, on_delete=models.CASCADE)
    assessment_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f"{self.student} {self.lecturer} {self.assessment_date}"
    
    def get_messages(self):

        return AssignmentMessages.objects.filter(assignment=self)
    

class AssignmentMessages(models.Model):

    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()

    

assignment/forms.py
from django import forms
from .models import Assignment
from users.models import Student

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ('lecturer',)

class DeRegistrationForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = ('status',)

assignment/views.py
from django.shortcuts import render, redirect
from .models import  Assignment
from .forms import AssignmentForm
from users.models import Employee, Student
from .forms import DeRegistrationForm

def assign_student(request, student_username):
    student = Student.objects.get(username=student_username)
    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.student = student
            assignment.save()
            return redirect('assignment:assignment_list')
    else:
        form = AssignmentForm()
    return render(request, 'assignment/assign_student.html', {'form': form, 'student':student})

def assignment_list(request):
    assignments = Assignment.objects.filter(student=request.user)
    return render(request, 'assignment/assignment_list.html', {'assignments': assignments})

#lecturer's view of the students that have been assigned to him
def view_assigned_students(request):
    lecturer = request.user
    assignments = Assignment.objects.filter(lecturer=lecturer)
    students = [assignment.student for assignment in assignments]
    return render(request, 'assignment/view_assigned_students.html', {'students': students})


# De-registration of students from the system
def initiate_de_registration(request, student_first_name):
	student = Student.objects.get(first_name=student_first_name)
	if request.user.employee.position == 'Lecturer' and request.user.employee in student.lecturers.all():
		student.status = 'pending_de_registration'
		student.save()
		return redirect('de_registration_pending')
	return render(request, 'assignments/error.html', {'message': 'Unauthorized'})

def approve_de_registration(request, student_first_name):
	student = Student.objects.get(first_name=student_first_names)
	if request.user.employee.position == 'Internship Coordinator' and student.status == 'pending_de_registration':
		student.delete()
		return redirect('de_registration_success')
	return render(request, 'assignments/error.html', {'message': 'Unauthorized'})

assignment/templates/assignment/approve_de_registration.html
<h1>Approve De-registration</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Approve De-registration</button>
</form>

assignment/templates/assignment/assign_student.html
<h2>Assign Students to Lecturers</h2>
<p>Student Name: {{student.first_name}} {{student.last_name}}</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Assign</button>
</form>

assignment/templates/assignment/assignment_list.html
<h1>Assignments</h1>
<ul>
    {% for assignment in assignments %}
        <li>
            {{ assignment.student.first_name }} {{ assignment.student.last_name }}-> <a href="{% url 'chat:private-room' assignment.id %}">{{ assignment.lecturer.first_name }} {{ assignment.lecturer.last_name }}</a> - {{ assignment.assessment_date }}
        </li>
    {% endfor %}
</ul>

assignment/templates/assignment/de_registration_pending.html
<h1>De-registration Pending</h1>
<p>The de-registration request has been sent to the internship coordinator for approval.</p>

assignment/templates/assignment/de_registration_success.html
<h1>De-registration Successful</h1>
<p>The student has been de-registered from the system.</p>

assignment/templates/assignment/error.html
<h1>Error</h1>
<p>{{ message }}</p>

assignment/templates/assignment/initiate_de_registration.html
<h1>Initiate De-registration</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Initiate De-registration</button>
</form>

assignment/templates/assignment/view_assigned_students.html
<h1>Assigned Students</h1>
<ul>
    {% for student in students %}
        <li>{{ student.name }} ({{ student.email }})</li>
    {% endfor %}
</ul>