chat/urls.py
from django.urls import path
from . import views


app_name = 'chat'

urlpatterns = [
    #calls
    path('chat', views.lobby, name='chat'),
    path('room/', views.room),
    path('get_token/', views.getToken),
    path('create_member/', views.createMember),
    path('get_member/', views.getMember),
    path('delete_member/', views.deleteMember),
    #messages
    path('message/', views.CreateRoom, name='create-room'),
    path('private-chat/<int:assignmemt_id>/', views.MessageView, name='private-room'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('',include('users.urls',namespace='users')),
    path('',include('chat.urls',namespace='chat')),
    path('',include('logbook.urls', namespace='logbook')),
    path('',include('assessment.urls', namespace='assessment')),
    path('',include('assignment.urls', namespace='assignment')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginPage, name="login-page"),
    path('logout/', views.logoutPage, name="logout-page"),
    path('register-student/', views.registerStudent, name="register-student"),
    path('register-staff/', views.registerStaff, name="register-staff"),
    path('lecturer_dashboard/', views.lecturer_dashboard, name='lecturer_dashboard'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('coordinator_dashboard/', views.coordinator_dashboard, name='coordinator_dashboard'),
    path('lecturer_student_detail/',views.lecturer_student_detail, name='lecturer_student_detail'),
    
    #De-regsistration
    path('students/<str:student_username>/deregister/', views.initiate_deregistration, name='initiate_deregistration'),
    path('deregistration_requests/<int:request_id>/approve/', views.approve_deregistration, name='approve_deregistration'),
    path('deregistration_requests/<int:request_id>/reject/', views.reject_deregistration, name='reject_deregistration'),
    
]

templates/home.html
{% extends "main.html" %}
{%block content%}
<h1>Welcome to the Home page</h1>
 {%endblock%}

templates/main.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" src="{% static "style.css" %}"/>

    <title>SRIAS</title>
  </head>

  <body>
    {%block content%}
    
    {% endblock %}
  </body>
</html>

templates/navbar.html
<!Doctype html>
<header>
    <div>
        <a href="{% url "home" %}">SRIAS</a>
    </div>
    <!--Logged In-->
    {%if request.user.is_authenticated%}
    <div>
        <p>
            {{request.user.username}}<span>@{{request.user.username}}</span>
        </p>
        <a href="{% url "users:logout-page" %}">Logout</a>
    </div>
    {%else%}
    <!--Not Logged In-->
    <a href="{% url "login-page" %}">Login</a>
    {%endif%}
</header>